[1m============================= test session starts ==============================[0m
platform linux -- Python 3.9.16, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /usr/local/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/airbyte-integrations/connectors/source-openweather/.hypothesis/examples')
rootdir: /airbyte-integrations/connectors/source-openweather/unit_tests, configfile: ../../../../pyproject.toml
plugins: mock-3.6.1, cov-3.0.0, requests-mock-1.9.3, timeout-1.4.2, hypothesis-6.54.6, sugar-0.9.7, custom-exit-code-0.3.0
[1mcollecting ... [0mcollected 31 items

unit_tests/test_extra_validations.py::test_check_lat[1-None0] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lat[1-None1] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lat[-12.3-None] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lat[-91-Wrong value for lat, it must be between -90 and 90] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lat[91-Wrong value for lat, it must be between -90 and 90] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lat[1,2-Wrong value for lat, it must be a decimal number between -90 and 90] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lat[foo-Wrong value for lat, it must be a decimal number between -90 and 90] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lat[lat_value7-Wrong value for lat, it must be a decimal number between -90 and 90] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lon[1-None0] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lon[1-None1] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lon[-92.3-None] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lon[-191-Wrong value for lon, it must be between -180 and 180] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lon[191-Wrong value for lon, it must be between -180 and 180] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lon[1,2-Wrong value for lon, it must be a decimal number between -180 and 180] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lon[foo-Wrong value for lon, it must be a decimal number between -180 and 180] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_check_lon[lon_value7-Wrong value for lon, it must be a decimal number between -180 and 180] [32mPASSED[0m
unit_tests/test_extra_validations.py::test_validate [32mPASSED[0m
unit_tests/test_source.py::test_check_connection[200] [32mPASSED[0m
unit_tests/test_source.py::test_check_connection[400] [32mPASSED[0m
unit_tests/test_source.py::test_check_connection_validation_error [32mPASSED[0m
unit_tests/test_source.py::test_streams [32mPASSED[0m
unit_tests/test_streams.py::test_request_params[stream0-expected_params0] [32mPASSED[0m
unit_tests/test_streams.py::test_request_params[stream1-expected_params1] [32mPASSED[0m
unit_tests/test_streams.py::test_request_params[stream2-expected_params2] [32mPASSED[0m
unit_tests/test_streams.py::test_parse_response[response_data0-stream_state0-True] [32mPASSED[0m
unit_tests/test_streams.py::test_parse_response[response_data1-stream_state1-True] [32mPASSED[0m
unit_tests/test_streams.py::test_parse_response[response_data2-stream_state2-False] [32mPASSED[0m
unit_tests/test_streams.py::test_should_retry[HTTPStatus.OK-False] [32mPASSED[0m
unit_tests/test_streams.py::test_should_retry[HTTPStatus.BAD_REQUEST-False] [32mPASSED[0m
unit_tests/test_streams.py::test_should_retry[HTTPStatus.TOO_MANY_REQUESTS-False] [32mPASSED[0m
unit_tests/test_streams.py::test_should_retry[HTTPStatus.INTERNAL_SERVER_ERROR-True] [32mPASSED[0m

[33m=============================== warnings summary ===============================[0m
../../../usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:45: 3 warnings
test_source.py: 1 warning
test_streams.py: 7 warnings
  /usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:45: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    self._authenticator: HttpAuthenticator = NoAuth()

../../../usr/local/lib/python3.9/site-packages/deprecated/classic.py:173: 3 warnings
test_source.py: 1 warning
test_streams.py: 7 warnings
  /usr/local/lib/python3.9/site-packages/deprecated/classic.py:173: DeprecationWarning: Call to deprecated class HttpAuthenticator. (Use requests.auth.AuthBase instead) -- Deprecated since version 0.1.20.
    return old_new1(cls, *args, **kwargs)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
[33m======================= [32m31 passed[0m, [33m[1m22 warnings[0m[33m in 0.55s[0m[33m ========================[0m
